services:
  - type: web
    name: motoventa
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://motoventa.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tuhost.mysql.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nombre_de_base
      - key: DB_USERNAME
        value: usuario
      - key: DB_PASSWORD
        value: clave
