services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:XXXXXXXXXXXXXXXXXXXXXXX
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tu-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: xxx
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nombre_db
      - key: DB_USERNAME
        value: usuario
      - key: DB_PASSWORD
        value: contraseña
